FROM elnomade/ubuntu:16.04
ENV REFRESHED_AT 2016-08-19

MAINTAINER Leonardo Luduena <lleo@linux.com>

# ensure local python is preferred over distribution python
ENV PATH /usr/local/bin:$PATH

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

# runtime dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    python3 -V


CMD ["python3"]
